name: Check Download Links

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
  push:
    paths:
      - 'bin/ltbox/config.json'
      - 'bin/ltbox/downloader.py'
      - '.github/workflows/link_check.yml'
      - '.github/workflows/python-command.yml'

jobs:
  check-urls:
    uses: ./.github/workflows/python-command.yml
    with:
      runner: ubuntu-latest
      python-version: '3.14'
      run-command: |
        python tests/scripts/check_links.py
