name: Lint Code

on:
  push:
    paths:
      - 'bin/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/lint.yml'
      - '.github/workflows/python-command.yml'
  pull_request:
    paths:
      - 'bin/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/lint.yml'
      - '.github/workflows/python-command.yml'

jobs:
  lint:
    uses: ./.github/workflows/python-command.yml
    with:
      runner: ubuntu-latest
      python-version: '3.14'
      run-command: |
        ruff check bin/ltbox tests
        ruff format --check bin/ltbox tests
        mypy bin/ltbox tests --ignore-missing-imports
