name: Lint Code

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    paths:
      - 'bin/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'bin/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/**'

jobs:
  lint:
    uses: ./.github/workflows/python-command.yml
    with:
      runner: ubuntu-latest
      python-version: '3.14'
      run-command: |
        ruff check bin/ltbox tests
        ruff format --check bin/ltbox tests
        mypy bin/ltbox tests --ignore-missing-imports
